0-transfer_file small mistake

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -6,21 +6,21 @@ if [ "$#" -lt 4 ];
 then
     echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
     exit 1
+else
+    # Assign values to variables from commandline
+    path_to_file="$1"
+    ip="$2"
+    username="$3"
+    path_to_ssh_key="$4"
+
+    #transfer file with scp
+    scp -o StrictHostKeyChecking=no -i "$path_to_file" "$path_to_file" "$username@$ip:~/"
+
+    # check the success of scp by checking exit status using $?
+    # if ["$?" -eq 0 ];
+    # then
+    #     echo "File transfered successfully."
+    # else
+    #     echo "failed to transfer file"
+    # fi
 fi
-
-# Assign values to variables from commandline
-path_to_file="$1"
-ip="$2"
-username="$3"
-path_to_ssh_key="$4"
-
-#transfer file with scp
-scp -o StrictHostKeyChecking=no -i "$path_to_file" "$path_to_file" "$username@$ip:~/"
-
-# check the success of scp by checking exit status using $?
-# if ["$?" -eq 0 ];
-# then
-#     echo "File transfered successfully."
-# else
-#     echo "failed to transfer file"
-# fi
