0-transfer_file less

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -18,9 +18,9 @@ path_to_ssh_key="$4"
 scp -o StrictHostKeyChecking=n0 -i "$path_to_file" "$path_to_file" "$username@$ip:~/"
 
 # check the success of scp by checking exit status using $?
-if ["$?" -eq 0 ];
-then
-    echo "File transfered successfully."
-else
-    echo "failed to transfer file"
-fi
+# if ["$?" -eq 0 ];
+# then
+#     echo "File transfered successfully."
+# else
+#     echo "failed to transfer file"
+# fi
